config-version: 2

name: 'asana'
version: '0.3.0'

require-dbt-version: [">=0.18.0", "<0.20.0"]

models:
    asana:
        +schema: asana
        materialized: table
        intermediate:
            materialized: ephemeral 

vars:
    asana: 
        project_task:   "{{ ref('stg_asana__project_task') }}"
        project:        "{{ ref('stg_asana__project') }}"
        section:        "{{ ref('stg_asana__section') }}"
        story:          "{{ ref('stg_asana__story') }}"
        tag:            "{{ ref('stg_asana__tag') }}"
        task_follower:  "{{ ref('stg_asana__task_follower') }}"
        task_section:   "{{ ref('stg_asana__task_section') }}"
        task_tag:       "{{ ref('stg_asana__task_tag') }}"
        task:           "{{ ref('stg_asana__task') }}"
        team:           "{{ ref('stg_asana__team') }}"
        user:           "{{ ref('stg_asana__user') }}"
        # Use to add custom fields to the tasks table
        task_enhanced_pass_through_columns: []
